# frozen_string_literal: true

require "English"
require "json"

# The bundled dataset refresh (data/vehicles.json), as a task so the
# provenance step and the country-rank merge can't be forgotten.
#
#   rake "data:refresh[v2026.10.0]"   # a published release TAG, never a branch
#
# Source: the public data repo at a release tag — dist/vehicles.json (the gem
# projection) unchanged, EXCEPT that each model gains `country_ranks`
# ({ "gb" => 2, … }) when the projection does not carry it yet. Those ranks
# are copied from the SAME tag's catalog/<kind>/models.json
# (popularity.by_country[cc].rank — open CC-BY data), keyed by the full
# kind/make/model id, so the merged file is what the pipeline's own projection
# emits once it ships the key (vehiclesdb-pipeline emit.rb write_dist_json!,
# 2026-10-10). When the projection DOES carry the key, the task asserts every
# rank equals the catalog's and aborts on any mismatch. Output formatting is
# the pipeline's (JSON.pretty_generate + "\n"); stripping `country_ranks`
# from the output gives back the release file byte for byte.
module DataRefresh
  module_function

  def git_show(repo, tag, path)
    out = IO.popen(["git", "-C", repo, "show", "#{tag}:#{path}"], &:read)
    abort "missing #{path} at #{tag}" unless $CHILD_STATUS.success?
    out
  end

  # "kind/make/model" => { "gb" => 2, … } for every ranked model at the tag.
  def catalog_ranks(repo, tag, kinds)
    kinds.each_with_object({}) do |kind, ranks|
      JSON.parse(git_show(repo, tag, "catalog/#{kind}/models.json")).each do |m|
        by_country = m.dig("popularity", "by_country") || {}
        r = by_country.filter_map { |cc, p| [cc, p["rank"]] if p["rank"] }.sort.to_h
        ranks["#{kind}/#{m["id"]}"] = r unless r.empty?
      end
    end
  end

  # Insert `country_ranks` where the pipeline emits it (right after
  # global_decile), or assert it when the projection already carries it.
  # Returns [merged, native] counts.
  def merge!(dist, ranks)
    merged = native = 0
    dist["makes"].each do |mk|
      mk["models"].each do |m|
        id = "#{m["kind"]}/#{mk["slug"]}/#{m["slug"]}"
        want = ranks[id]
        if m.key?("country_ranks")
          native += 1
          abort "country_ranks mismatch for #{id}" unless m["country_ranks"] == want
        elsif want
          m.replace(with_ranks(m, want))
          merged += 1
        end
      end
    end
    [merged, native]
  end

  def with_ranks(model, ranks)
    out = model.each_with_object({}) do |(k, v), h|
      h[k] = v
      h["country_ranks"] = ranks if k == "global_decile"
    end
    out["country_ranks"] ||= ranks
    out
  end

  def provenance(tag, commit, version, merged, native)
    <<~MD
      # Bundled vehicles dataset

      `data/vehicles.json` is the public data repo's `dist/vehicles.json`
      (the gem projection) at a release tag:

      - **Source**: https://github.com/vehiclesdb/vehiclesdb `dist/vehicles.json`
      - **Tag**: `#{tag}` (commit `#{commit}`), dataset version `#{version}`
      - **country_ranks**: #{native} model(s) carried it natively; #{merged} merged from
        the same tag's `catalog/<kind>/models.json` `popularity.by_country[cc].rank`
      - **License**: CC-BY 4.0 (see the data repo's LICENSE + ATTRIBUTION.md)

      Refresh: `rake "data:refresh[<tag>]"` (this file is generated by it).
    MD
  end
end

namespace :data do
  desc "Refresh data/vehicles.json from a release tag of the local dataset repo"
  task :refresh, [:tag] do |_t, args|
    tag = args[:tag] or abort 'usage: rake "data:refresh[vYYYY.MM.P]" (a release tag)'
    root = File.expand_path("..", __dir__)
    repo = File.expand_path(ENV.fetch("VDB_DATA_REPO", "~/GitHub/vehiclesdb"))
    sh "git -C #{repo} fetch origin --tags -q"
    commit = `git -C #{repo} rev-parse #{tag}^{commit}`.strip
    abort "unknown tag #{tag}" unless $CHILD_STATUS.success? && !commit.empty?

    dist = JSON.parse(DataRefresh.git_show(repo, tag, "dist/vehicles.json"))
    merged, native = DataRefresh.merge!(dist, DataRefresh.catalog_ranks(repo, tag, dist["kinds"]))
    File.write("#{root}/data/vehicles.json", "#{JSON.pretty_generate(dist)}\n")
    File.write("#{root}/data/PROVENANCE-vehicles.md",
               DataRefresh.provenance(tag, commit, dist["version"], merged, native))
    puts "data refreshed to #{tag} (#{dist["version"]}): #{merged} merged, #{native} native country_ranks"
  end
end
