# The plates-data refresh, as a task so the PROVENANCE step can't be
# forgotten (it is gem-local; a bare rm+archive deletes it silently —
# that shipped once in 0.7.4 and broke consumers reading the pin).
namespace :plates do
  desc "Refresh data/plates from the local dataset repo's origin/main"
  task :refresh do
    root = File.expand_path("..", __dir__)
    ds = File.expand_path("~/GitHub/vehiclesdb")
    sh "git -C #{ds} fetch origin -q"
    rm_rf "#{root}/data/plates"
    mkdir_p "#{root}/data/plates"
    sh "git -C #{ds} archive origin/main plates | tar -x --exclude 'plates/_art' -C #{root}/data/"
    rm_rf "#{root}/data/plates/_art"
    commit = `git -C #{ds} rev-parse origin/main`.strip
    File.write("#{root}/data/plates/PROVENANCE.md", <<~MD)
      # Bundled plates dataset (PRD-PLATES, full corpus)

      Copy of `plates/` from the public data repo (EXCLUDING `_art/`),
      refreshed on gem releases:

      - **Source**: https://github.com/vehiclesdb/vehiclesdb `plates/`
      - **Commit**: `#{commit}`
      - **License**: CC-BY 4.0 (see the data repo's LICENSE + ATTRIBUTION.md)

      Refresh: `rake plates:refresh` (this file is generated by it).
    MD
    puts "plates refreshed at #{commit}"
  end
end
